# Generated by Django 5.2.4 on 2025-07-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_remove_book_libraries_remove_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book')]},
        ),
    ]
