# Generated by Django 5.2.4 on 2025-07-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book'), ('can_change_book', 'Can change book')]},
        ),
    ]
