from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token
from .views import BookList, BookViewSet

# Create a router and register the ViewSet
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Token auth endpoint
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    # List-only endpoint
    path('books/', BookList.as_view(), name='book-list'),

    # Include all routes generated by the router
    path('', include(router.urls)),
]
